CREATE TABLE IF NOT EXISTS todos (
	id INTEGER PRIMARY KEY,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	title TEXT NOT NULL,
	done BOOLEAN DEFAULT 0 NOT NULL
);
